### ISSUE TITLE
access events in function

### ISSUE THREAD

**Issue by botjaeger** [CodingZeal/react-native-appstate-listener#3]
Hello, I know this is a bit noob question but please do answer...

based on your documentation,
`<AppStateListener
        onActive={handleActive}
        onBackground={handleBackground}
        onInactive={handleInactive}
      />`
I'd like to access those 2 events (`onActive`, `onBackground`) from any function like `componentWillMount` or any custom function.

**Comment by randycoulman** [comment]
Hi @aanthraxx.  I'm not sure I understand your question.  I'll provide a bit more information here in the hopes that it will help, but if you could provide more detail on what you're trying to do, that would allow me to give you a better response.

When you use `<AppStateListener ... />` in your `render` function, the `onActive`, `onBackground`, and `onInactive` props you provide are functions defined in your code.  Because of that, you can also call those functions from your own custom functions or `componentWillMount`, etc.

However, the whole purpose of `AppStateListener` is to call those functions for you at the appropriate time.  Specifically, when your component mounts, `AppStateListener` will also mount and will call the `onActive` callback for you.  So there should be no need for you to call it from your own `componentWillMount` or `componentDidMount` function.  There's nothing stopping you from doing that, but you shouldn't need to.

If this doesn't answer your question, please provide more information and/or a code sample of what you're trying to do.

**Comment by randycoulman** [comment]
Closing.  If there are still questions here, please open a new issue with additional details.
